---
# This playbook installs Apache
- name: install and start postgresql
  hosts: database
  vars:
    psql_user: db_user
    psql_pass: secret_password
  remote_user: root


  tasks:
    - name: PostgreSQL | Make sure the dependencies are installed
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - "python-psycopg2"
        - "python-pycurl"
        - "glibc-common"

    - name: PostgreSQL | Install PostgreSQL
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - "postgresql-server"
        - "postgresql"
        - "postgresql-contrib"

    - name: PostgreSQL | Make sure the postgres data directory exists
      file:
        path: "/var/lib/pgsql/data"
        owner: "postgres"
        group: "postgres"
        state: directory
        mode: 0700
      register: pgdata_dir_exist

    - name: PostgreSQL | Initialize the database | RedHat
      command: >
        postgresql-setup initdb
      become: yes
      become_user: postgres
      # when: pgdata_dir_exist.changed

    - name: start PostGreSQL
      service: name=postgresql state=started enabled=yes

    - name: Add a database
      postgresql_db:
        name: demo_db
        state: present
      become_user: postgres
      become: true
