---
# This playbook installs MySQL
- name: install and start MySQL (mariadb)
  hosts: database
  vars:
    sql_user: db_user
    sql_pass: secret_password
  remote_user: root


  tasks:

    - name: Install MySQL (mariadb)
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - mariadb
        - mariadb-server
        - mariadb-libs

    - name: Install Ansible Management packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - MySQL-python
        - perl-DBD-MySQL

    - name: Start and enable MySQL (mariadb)
      service:
        name: mariadb
        state: started
        enabled: "Yes"

    - name: Add new database
      mysql_db:
        name: demodata
        state: present

    - name: Add User to MySQL
      mysql_user:
        name: "{{ sql_user }}"
        password: "{{ sql_pass }}"
        priv: '*.*:ALL'
        state: present
