---
# This is a comment
- name: Lay down a simple file
  hosts: centos
  remote_user: root
  vars:
    foobar: "This is some text"
    tempdest: "/root/somefile.txt"
  tasks:

    - name: Lay down template file
      template:
        src: templates/sometemplate.j2
        dest: "{{ tempdest }}"
        owner: root
        group: root
        mode: 0600
